version: '3.6'
services:
  nginx_main:
    platform: linux/x86_64
    container_name: load_balancer 
    image: shashwot/nginx-more
    restart: always
    network_mode: "host"
    ports:
      - "80:80"
    volumes:
      - "./nginx/load_balancer/load_balancer.conf:/etc/nginx/nginx.conf"
      - "./nginx/load_balancer/GeoLite2-Country.mmdb:/var/lib/GeoIP/GeoLite2-Country.mmdb"

  web_us:
    platform: linux/x86_64
    image: nginx:alpine
    restart: always
    volumes:
      - "./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/html/index-us.html:/var/www/html/index.html"
    ports:
      - '8080:80'

  web_us_2:
    platform: linux/x86_64
    image: nginx:alpine
    restart: always
    volumes:
      - "./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/html/index-us-2.html:/var/www/html/index.html"
    ports:
      - '8081:80'

  web_uk:
    platform: linux/x86_64
    image: nginx:alpine
    restart: always
    volumes:
      - "./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/html/index-uk.html:/var/www/html/index.html"
    ports:
      - '8082:80'

  web_rest_users:
    platform: linux/x86_64
    image: nginx:alpine
    restart: always
    volumes:
      - "./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/html/index-rest-users.html:/var/www/html/index.html"
    ports:
      - '8083:80'

  web_backup:
    platform: linux/x86_64
    image: nginx:alpine
    restart: always
    volumes:
      - "./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/html/index-backup.html:/var/www/html/index.html"
    ports:
      - '8084:80'
